# Generated by Django 5.2.9 on 2026-04-21 00:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0003_comment_favorite_hymnaudio"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.AddField(
            model_name="hymn",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="hymn",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="hymn_search_vector_gin"),
        ),
    ]
