# Generated by Django 5.2.9 on 2026-04-27 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0005_backfill_search_vector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_page", models.PositiveIntegerField(default=0, verbose_name="Página atual")),
                ("total_pages", models.PositiveIntegerField(default=0, verbose_name="Total de páginas")),
                ("result_data", models.JSONField(blank=True, null=True, verbose_name="Dados do resultado")),
                ("error_message", models.TextField(blank=True, verbose_name="Erro")),
                ("pdf_filename", models.CharField(blank=True, max_length=255, verbose_name="Nome do PDF")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Iniciado em")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Finalizado em")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa OCR",
                "verbose_name_plural": "Tarefas OCR",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="hymns_ocrta_user_id_9c68b4_idx"),
                    models.Index(fields=["status"], name="hymns_ocrta_status_ff82a3_idx"),
                ],
            },
        ),
    ]
