# Generated by Django 5.2.9 on 2026-04-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0006_ocrtask"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
