# Generated by Django 5.2.9 on 2026-04-28 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0009_hymnbook_publication_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hymn",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Última revisão em"),
        ),
        migrations.AddField(
            model_name="hymn",
            name="last_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_hymns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Última revisão por",
            ),
        ),
        migrations.AddField(
            model_name="hymn",
            name="review_status",
            field=models.CharField(
                choices=[("not_reviewed", "Não revisado"), ("in_review", "Em revisão"), ("reviewed", "Revisado")],
                db_index=True,
                default="not_reviewed",
                max_length=20,
                verbose_name="Status de revisão",
            ),
        ),
        migrations.AddField(
            model_name="hymn",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("ocr", "OCR"), ("yaml", "YAML")],
                default="manual",
                help_text="Como o hino foi cadastrado (manual, OCR, YAML)",
                max_length=10,
                verbose_name="Origem",
            ),
        ),
        migrations.CreateModel(
            name="HymnRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revised_at", models.DateTimeField(auto_now_add=True, verbose_name="Revisado em")),
                ("previous_status", models.CharField(blank=True, max_length=20, verbose_name="Status anterior")),
                ("new_status", models.CharField(blank=True, max_length=20, verbose_name="Novo status")),
                (
                    "change_summary",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional das mudanças feitas pelo revisor",
                        verbose_name="Resumo da mudança",
                    ),
                ),
                (
                    "field_diff",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot dos campos alterados: {field: {old, new}}",
                        verbose_name="Diff de campos",
                    ),
                ),
                (
                    "hymn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="hymns.hymn",
                        verbose_name="Hino",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hymn_revisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisão de hino",
                "verbose_name_plural": "Revisões de hinos",
                "ordering": ["-revised_at"],
                "indexes": [models.Index(fields=["hymn", "-revised_at"], name="hymns_hymnr_hymn_id_5333d6_idx")],
            },
        ),
    ]
