# Generated by Django 5.2.9 on 2026-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0010_hymn_review_state_and_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="hymn",
            name="ocr_avg_confidence",
            field=models.FloatField(blank=True, null=True, verbose_name="Confiança média do OCR (0-100)"),
        ),
        migrations.AddField(
            model_name="hymn",
            name="ocr_text",
            field=models.TextField(
                blank=True,
                help_text="Texto cru extraído pelo OCR antes de revisão editorial",
                verbose_name="Texto OCR original",
            ),
        ),
    ]
