# Generated by Django 5.2.9 on 2026-04-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0011_hymn_ocr_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="hymnbook",
            name="accent_color",
            field=models.CharField(
                blank=True,
                help_text="Hex (ex.: #8C3A2E). Vazio: cor escolhida deterministicamente pela paleta.",
                max_length=7,
                verbose_name="Cor de destaque",
            ),
        ),
    ]
