# Generated by Django 5.2.9 on 2026-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0012_hymnbook_accent_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="hymnaudio",
            name="waveform_peaks",
            field=models.JSONField(blank=True, default=list, verbose_name="Picos da waveform"),
        ),
    ]
