# Generated by Django 5.2.9 on 2026-05-04 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0013_hymnaudio_waveform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hymnaudio",
            name="is_match",
            field=models.BooleanField(
                blank=True, help_text="True/False/None (não revisado)", null=True, verbose_name="Confere com o hino?"
            ),
        ),
        migrations.AddField(
            model_name="hymnaudio",
            name="mismatch_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("other_hymn", "É outro hino"),
                    ("incomplete", "Áudio cortado/incompleto"),
                    ("wrong_lyrics", "Letra diferente"),
                    ("inaudible", "Áudio inaudível"),
                    ("other", "Outro"),
                ],
                help_text="Só preenchido quando is_match=False",
                max_length=20,
                verbose_name="Motivo de mismatch",
            ),
        ),
        migrations.AddField(
            model_name="hymnaudio",
            name="quality_observations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de strings em QUALITY_OBSERVATIONS",
                verbose_name="Observações de qualidade",
            ),
        ),
        migrations.AddField(
            model_name="hymnaudio",
            name="quality_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1 a 5, só preenchido quando is_match=True",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="Qualidade",
            ),
        ),
        migrations.AddField(
            model_name="hymnaudio",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Revisado em"),
        ),
        migrations.AddField(
            model_name="hymnaudio",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hymn_audio_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por",
            ),
        ),
    ]
