# Generated by Django 5.2.13 on 2026-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0014_hymnaudio_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="hymn",
            name="section",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subgrupo dentro do hinário (ex.: 'Offered to Sônia Palhares' em Firmado na Luz)",
                max_length=200,
                verbose_name="Seção",
            ),
        ),
    ]
