# Generated by Django 5.2.13 on 2026-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0015_hymn_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="hymnbook",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Aparece com prioridade na seção 'Em destaque' da home (rotação por hora).",
                verbose_name="Em destaque",
            ),
        ),
        migrations.AddField(
            model_name="hymnbook",
            name="priority",
            field=models.CharField(
                choices=[("P1", "P1 — alta urgência"), ("P2", "P2 — média"), ("P3", "P3 — baixa")],
                db_index=True,
                default="P3",
                help_text="Define a urgência da revisão na fila de revisão (P1 = mais urgente).",
                max_length=2,
                verbose_name="Prioridade de revisão",
            ),
        ),
    ]
