# Generated by Django 5.2.13 on 2026-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0016_hymnbook_priority_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="hymnbook",
            name="sync_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Incrementa a cada mudança em hinos/áudios. Usado pelo cliente offline.",
                verbose_name="Versão de sincronização",
            ),
        ),
    ]
